formulario/urls.py
from django.contrib import admin
from django.urls import include, path

from formulario import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('deletar/<int:id_formulario>',views.deletar_formulario,name='deletar'),
    path('novo/', views.cria_formulario, name='criar_formulario'),
    path('formulario-feito/', views.formulario_feito, name='formulario_feito') ,
    path('cadastro/', views.cadastro , name='cadastro') ,
    path('perguntas_de_texto/',views.perguntas_de_texto,name='pergunta_de_texto') ,
    path('perguntas-feitas/', views.perguntas_feitas, name='perguntas_feitas') ,
    path('listagem-perguntas/', views.listagem_perguntas, name='listagem_perguntas'),
    path('editar/<int:id_formulario>',views.edita_formulario,name='editar') ,
    path('deletar-pergunta/<int:id_pergunta>',views.deletar_perguntas,name='deletar_pergunta'),
    path('perguntas_forms/<int:id_formulario>', views.listagem_perg_em_forms, name='perguntas_forms'),
    path('adicionar-pergunta/<int:id_pergunta>',views.listagem_formularios, name='adicionar_pergunta'),
    path('add-pergunta/',views.adicionar_pergunta, name='add_pergunta'),
    path('editar-pergunta/<int:id_pergunta>', views.editar_perguntas, name='editar-pergunta'),
    path('selecionar-tipo/',views.seleciona_tipo, name='tipo_da_pergunta') ,
    path('perguntas_de_intervalo/',views.perguntas_de_intervalo,name='pergunta_de_intervalo'),
    path('remover-pergunta/', views.remover_pergunta, name='remover_pergunta') ,
    path('gerar-pdf/<int:id_formulario>/', views.gerar_pdf, name='gerar_pdf'),
    path('formulario/<int:id_formulario>/', views.form_detalhes, name='formulario'),
    ]


#{% url 'perguntas_forms' formulario.id %}

getit/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include('formulario.urls')),

]

formulario/models.py
from django.db import models

# Create your models here.
from django.db import models

class Formulario(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField(max_length=2000, blank=True, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    def __str__(self):
        return self.nome

class Perguntas (models.Model):
    pergunta_de_texto = models.TextField(max_length=2000, blank=True, null=True) ## classe para todos os tipos de pergunta (nome da variável está específico, mas devemos ignorar, só não trocamos porque ia quebrar todo o dódigo - ficaria melhor: 'pergunta')
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return self.pergunta_de_texto
    
class Intervalos(models.Model):
    enunciado_pergunta = models.ForeignKey(Perguntas, on_delete=models.CASCADE)
    intervalo = models.PositiveIntegerField()
    
    def __str__(self):
        return self.intervalo
    
class FormularioPergunta(models.Model):
    formulario = models.ForeignKey(Formulario, on_delete=models.CASCADE)
    pergunta = models.ForeignKey(Perguntas, on_delete=models.CASCADE)
    def __str__(self):
        return self.formulario.nome + ' - ' + self.pergunta.pergunta_de_texto

formulario/views.py
from django.shortcuts import redirect, render,get_object_or_404,HttpResponseRedirect
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas


def cadastro(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        sobrenome = request.POST.get('sobrenome')
        email = request.POST.get('e-mail')
        usuario = request.POST.get('usuário')
        cria_senha = request.POST.get('senha')
        # confirma_senha = request.POST.get('confirme sua senha')
        new_form = User.objects.create_user(username=usuario, first_name=nome, last_name=sobrenome, email=email, password=cria_senha)
        # create não pede save

        return redirect('index')

    else:
        return render(request, 'registration/cadastro.html')


@login_required 
def index(request):
    # print(request.user, request.user.first_name, request.user.last_name)
    all_forms = Formulario.objects.filter(author=request.user).order_by('-data_criacao')
    print(all_forms)
    return render(request, 'formulario/index.html', {'formularios': all_forms, 'user': request.user})

@login_required 
def cria_formulario(request) :
    if request.method == 'POST' :
        nome = request.POST.get('nome')
        descricao = request.POST.get('descricao')
        pergunta = request.POST.get('pergunta')
        author=request.user
        formulario = Formulario(nome=nome, descricao=descricao,author=author)
        formulario.save()
        return redirect('formulario_feito')
    else :
        return render(request, 'formulario/criar_formulario.html')
@login_required
def edita_formulario(request,id_formulario):
    form=get_object_or_404(Formulario,id=id_formulario)
    if request.method == 'POST':
        
        form.nome = request.POST.get('nome')
        form.descricao = request.POST.get('descricao')
        form.save()
        return redirect('index')
    else:
        return render(request, 'formulario/editar_formulario.html', {'formulario': form})
    
def form_detalhes(request, id_formulario):
    form = Formulario.objects.prefetch_related('formulariopergunta_set__pergunta').get(id=id_formulario)
    return render(request, 'formulario/formulario.html', {'form': form})

@login_required 
def formulario_feito(request) :
    return render(request, 'formulario/formulario_feito.html')

def deletar_formulario(request,id_formulario):
    form=get_object_or_404(Formulario,id=id_formulario)
    if request.method=='POST':
        form.delete()
        return redirect('index')
    else:
        return HttpResponseRedirect('/')
    
@login_required
def perguntas_de_texto(request):
    if request.method == 'POST':
        pergunta_de_texto = request.POST.get('pergunta de texto')
        tipo = 'texto'
        perguntas= Perguntas.objects.create(pergunta_de_texto=pergunta_de_texto, tipo=tipo)

        return redirect('perguntas_feitas')
    else :
        return render(request, 'perguntas/pergunta_de_texto.html')

@login_required
def listagem_perg_em_forms(request, id_formulario):
    perguntas = Perguntas.objects.all()
    formulario = Formulario.objects.get(id=id_formulario)
    relacoes = FormularioPergunta.objects.filter(formulario=formulario)
    ids_perguntas = []
    for rel in relacoes:
        ids_perguntas.append(rel.pergunta.id)

    return render(request, 'formulario/perguntas_form.html', {'perguntas_de_texto': perguntas, 'ids_perguntas': ids_perguntas, 'id_formulario':id_formulario})


def perguntas_de_intervalo(request):
    if request.method == 'POST':
        enunciado = request.POST.get('pergunta de intervalo')
        intervalo = request.POST.get('intervalo')
        tipo = 'intervalo'
        pergunta_de_intervalo = Perguntas.objects.create(pergunta_de_texto=enunciado, tipo=tipo)
        Intervalos.objects.create(enunciado_pergunta=pergunta_de_intervalo, intervalo=intervalo)
        return redirect('perguntas_feitas')
    else :
        return render(request, 'perguntas/pergunta_de_intervalo.html')


def seleciona_tipo(request):
    if request.method == 'POST':
        tipo_da_pergunta = request.POST.get('tipo da pergunta')
        if tipo_da_pergunta == 'texto':
            return redirect('pergunta_de_texto')
        elif tipo_da_pergunta == 'intervalo':  
            return redirect('pergunta_de_intervalo')

        return redirect('perguntas_feitas')
    else :
        return render(request, 'perguntas/tipo_da_pergunta.html')


@login_required
def perguntas_feitas(request):
   return render(request, 'perguntas/perguntas_feitas.html')

@login_required
def listagem_perguntas(request):
    perguntas = Perguntas.objects.all()
    return render(request, 'perguntas/listar_perguntas.html', {'perguntas_de_texto': perguntas})

# Função que adiciona pergunta ao formulário
def listagem_formularios(request, id_pergunta):
    if request.method == 'POST':
        all_forms = Formulario.objects.filter(author=request.user).order_by('-data_criacao')
        return render(request, 'formulario/adicionar_pergunta.html', {'formularios': all_forms, 'id_pergunta': id_pergunta})
    
def adicionar_pergunta(request):
    if request.method == 'POST':
        id_formulario = request.POST.get('id_formulario')
        id_pergunta = request.POST.get('id_pergunta')
        formulario = Formulario.objects.get(id=id_formulario)
        pergunta = Perguntas.objects.get(id=id_pergunta)
        FormularioPergunta.objects.create(formulario=formulario, pergunta=pergunta) 
        return redirect('perguntas_forms', id_formulario=id_formulario)
    else:
        return HttpResponseRedirect('/')

def listagem_perguntas(request):
    perguntas = Perguntas.objects.all()
    return render(request, 'perguntas/listar_perguntas.html', {'perguntas_de_texto': perguntas})

def deletar_perguntas(request,id_pergunta):
    perg=get_object_or_404(Perguntas,id=id_pergunta)

    perg.delete()
    return redirect('listagem_perguntas')


def editar_perguntas(request, id_pergunta):
    intervalo = ''
    perg = get_object_or_404(Perguntas, id=id_pergunta)
    if perg.tipo == 'intervalo':
        intervalo = get_object_or_404(Intervalos, enunciado_pergunta = perg)

        perg.save()
    if request.method== 'POST':
        perg.pergunta_de_texto = request.POST.get('pergunta_de_texto')
        perg.save()

        if perg.tipo == 'intervalo':
            intervalo.intervalo = request.POST.get('pergunta_de_intervalo')
            intervalo.save()
        
        return redirect('listagem_perguntas')                                       ##-- nome inventado que vai ser usado no template
    else :
        return render(request,'perguntas/editar_pergunta.html', {'pergunta': perg , 'intervalo': intervalo})

def remover_pergunta (request) :
    if request.method == 'POST':
        id_formulario = request.POST.get('id_formulario')
        id_pergunta = request.POST.get('id_pergunta')
        formulario = Formulario.objects.get(id=id_formulario)
        pergunta = Perguntas.objects.get(id=id_pergunta)
        deletar = FormularioPergunta.objects.filter(formulario=formulario, pergunta=pergunta) 
        deletar.delete()
        return redirect('perguntas_forms', id_formulario=id_formulario)
    else:
        return HttpResponseRedirect('/')   

def gerar_pdf(request, id_formulario):

    buffer = io.BytesIO()

    p = canvas.Canvas(buffer)

    formulario = Formulario.objects.get(id=id_formulario)
    formP = FormularioPergunta.objects.filter(formulario=formulario)

    # intervalo = Formulario.objects.get(id= #)
    # interv = Intervalos.objects.filter()

    x = 20
    y = 480
    page_height = 720  # Assuming a standard A4 page height

    p.drawString(230, 720, formulario.nome)
    p.drawString(0, 600, formulario.descricao)

    space_between_questions = 100  # Adjust this value for desired spacing

    for fP in formP:
        if y - space_between_questions <= 50:  # If remaining space on the page is not sufficient, start a new page
            p.showPage()  # Start a new page
            p.drawString(230, 720, formulario.nome)
            p.drawString(0, 660, formulario.descricao)
            y = page_height - 120  # Reset y position for the new page

        p.drawString(x, y, fP.pergunta.pergunta_de_texto)
        y -= space_between_questions + 150  # Move to the next line with space between questions

    # for fP in formP:
    #     if y - space_between_questions <= 50:  # If remaining space on the page is not sufficient, start a new page
    #         p.showPage()  # Start a new page
    #         p.drawString(230, 720, formulario.nome)
    #         p.drawString(0, 660, formulario.descricao)
    #         y = page_height - 120  # Reset y position for the new page


    #     p.drawString(x, y, fP.pergunta.pergunta_de_texto)
    #     y -= space_between_questions + 150  # Move to the next line with space between questions

    p.showPage()  # Close the last page

    p.save()

    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='formulario.pdf')

formulario/templates/formulario/adicionar_pergunta.html
{% extends 'formulario/base.html' %}
{% block content %}

<div class="forms">
    <i class="bi bi-arrow-left-circle-fill"></i>   <h2>Formulários</h2>

    <form action="/add-pergunta/" method="POST">
        {% csrf_token %}
        <label for="formulario">Selecione um formulário:</label>
        <!-- campo hidden para passar o id da pergunta -->
        <input type="hidden" name="id_pergunta" value="{{ id_pergunta }}">
        <select name="id_formulario" id="formulario">
            {% for formulario in formularios %}
                <option value="{{ formulario.id }}">{{ formulario.nome }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="adicionar-pergunta">Adicionar</button>
    </form>
    
</div>
{% endblock %}

formulario/templates/formulario/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Gestão de Formulários</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>
  <body>
    <!-- logout apenas se já tiver logado -->
    {% if user.is_authenticated %}  
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="sair">sair</button>
    </form>      
    <a href="{% url 'index' %}" 
    class="sair">Início</a> <!-- Aparece em todas as páginas-->
    {% endif %}

    <main class="container">{% block content %}{% endblock %}</main>
  </body>
</html>

formulario/templates/formulario/criar_formulario.html
{% extends "formulario/base.html" %}

{% block content %}

<h2 class="text-center">Criar Formulário</h2>
<main>
    <form method="post" class="box"> 
        {% csrf_token %}
        <div class="input-container">
            <label for="nome">Titulo:</label>
            <input type="text" id="nome" name="nome" required class="input-container input">
        </div>
        
        <div class="input-container">
            <label for="descricao">Descrição:</label>
            <input id="descricao" name="descricao" class="input-container input"></input>
            
        </div>
        
        <button type="submit" class="btn">Enviar</button>
    </form>
</main>

{% endblock %}

formulario/templates/formulario/editar_formulario.html
{% extends "formulario/base.html" %}

{% block content %}

<h2 class="text-center">Editar Formulário</h2>
<main>
    <form method="post" class="box"> 
        {% csrf_token %}
        <div class="input-container">
            <label for="nome">Título:</label>
            <input type="text" id="nome" name="nome" required class="input-container input" value="{{ formulario.nome }}">
        </div>
        <div class="input-container">
            <label for="descricao">Descrição:</label>
            <input type="text" id="descricao" name="descricao" required class="input-container input" value="{{ formulario.descricao }}">
        </div>
        
        <!-- Botão para salvar as alterações do formulário -->
        <button type="submit" class="btn">Salvar</button>
    </form>

    <a href="{% url 'perguntas_forms' formulario.id %}" class="btn">Gerenciar Perguntas</a>
</main>

{% endblock %}

formulario/templates/formulario/formulario.html
{% extends "formulario/base.html" %}

{% block content %}

<main>
    <div class="container-unico">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Detalhe do Formulário</title>
        </head>
        <body>
            <div class="cabecalho-formulario">
                <h1 class="titulo-principal">{{ form.nome }}</h1>
                <p class="descricao-form">{{ form.descricao }}</p>
            </div>
            
            <h2 class="titulo-pergunta">Perguntas:</h2>
            <ul class="lista-perguntas">
                {% for form_pergunta in form.formulariopergunta_set.all %}
                    <li class="item-pergunta">{{ form_pergunta.pergunta.pergunta_de_texto }}</li>
                {% endfor %}
            </ul>
        </body>
    </div>
</main>    

{% endblock %}

formulario/templates/formulario/formulario_detalhes.html
{% extends "formulario/base.html" %}

{% block content %}
<header>
    <h1>Detalhes do Formulário</h1>
</header>

<main>
    <div class="container">
        <h2>{{ formulario.nome }}</h2>
        <p>{{ formulario.descricao }}</p>
        <!-- Add any other information you want to display about the form here -->
        <form action="{% url 'deletar' formulario.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="deletar-formulario">Deletar</button>
        </form>
    </div>
</main>

<footer>
    <p>&copy; 2024 Sistema de Gestão de Formulários. Todos os direitos reservados.</p>
</footer>
{% endblock %}

formulario/templates/formulario/formulario_feito.html
{% extends "formulario/base.html" %}

{% block content %}

<div class="form-success-container">
    <h2 class="form-success-title">Formulário criado com sucesso!</h2>

    <div class="form-success-buttons">
        <a href="{% url 'criar_formulario' %}" class="btn form-success-btn">Criar outro Formulário</a>
        <a href="{% url 'index' %}" class="btn form-success-btn">Voltar para o Início</a>
        <a href="{% url 'perguntas_feitas' %}" 
        class="btn form-success-btn">Veja as perguntas já existentes</a> 

    </div>
</div>

{% endblock %}

formulario/templates/formulario/index.html
{% extends "formulario/base.html" %}

{% block content %}

<header>
    <h1>Sistema de Gestão de Formulários</h1>
</header>
<main>
    <div class="container">
        <h2>Bem-vindo!</h2>
        <p>Com nosso sistema, você pode criar formulários personalizados e gerar PDFs para suas pesquisas.</p>
        <div class="buttons-container">
            <a class="button" href="/novo">Criar Novo Formulário</a>
            <a class="button" href="/selecionar-tipo/">Criar nova pergunta</a>
            <a class="button" href="{% url 'listagem_perguntas' %}" >Consulte aqui as perguntas já existentes</a>
        </div>
    </div>

    {% for formulario in formularios %}
    <div class="caixas container">
        <a href="{% url 'formulario' formulario.id %}" class="link">{{ formulario.nome }}</a>  
        <p class="caixas-descricao">{{ formulario.descricao }}</p>
        <div class="para_lado">
            <form action="{% url 'editar' formulario.id %}" method="GET">
                {% csrf_token %}
                <button type="submit" class="editar-formulario">Editar</button>
            </form>
            <form action="{% url 'gerar_pdf' formulario.id %}" method="GET">
                {% csrf_token %}
                <button type="submit" class="button-pdf ">Gerar PDF</button>
            </form>
            <form action="{% url 'deletar' formulario.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="deletar-formulario">Deletar</button>
            </form>
        </div>
    </div>
    {% endfor %}
</main>

<footer>
    <p>&copy; 2024 Sistema de Gestão de Formulários. Todos os direitos reservados.</p>
</footer>

{% endblock %}

formulario/templates/formulario/listar_formularios.html
{% extends 'formulario/base.html' %}
{% block content %}

<div class="forms">
    <i class="bi bi-arrow-left-circle-fill"></i>   <h2>Formularios</h2>

    <ul>
        {%for formulario in formularios%}
        <li>{{formulario.nome}}</li>
        {% endfor %}
</div>
{% endblock %}

formulario/templates/formulario/perguntas_form.html
{% extends 'formulario/base.html' %}
{% block content %}

<div class="forms">
    <i class="bi bi-arrow-left-circle-fill"></i><h2>Formulários - Perguntas</h2>
    <ul>
        {% for pergunta in perguntas_de_texto %}
        <li>{{ pergunta.pergunta_de_texto }} - 
            {% if pergunta.id in ids_perguntas %}
            <form action="/remover-pergunta/" method="post">
                {% csrf_token %}
                <input type="hidden" name="id_pergunta" value="{{ pergunta.id }}">
                <input type="hidden" name="id_formulario" value="{{ id_formulario }}">
                <button type="submit" class="button-vermelho">Remover</button>
            </form>
            {% else %}
            <form action="/add-pergunta/" method="post">
                {% csrf_token %}
                <input type="hidden" name="id_pergunta" value="{{ pergunta.id }}">
                <input type="hidden" name="id_formulario" value="{{ id_formulario }}">
                <button type="submit" class="button">Adicionar</button>
            </form>
            {% endif %}
        </li>
        {% empty %}
        <li>Nenhuma pergunta cadastrada.</li>
        {% endfor %}
    </ul>
    
</div>

{% endblock %}

formulario/templates/formulario/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ form.id }} - {{ form.nome }}

    <form action="{% url 'update' note.id%}" method="POST">
        {% csrf_token %}
        <label for="titulo">Título</label>
        <input id="titulo" type="text" name="titulo" value="{{note.title}}"/>
      
        <label for="descricao">Descricao</label>
        <textarea id="descricao" name="descricao">{{form.descricao}}</textarea>

        <label for="pergunta">Perguntas</label>
        {{ % for pergunta in perguntas % }}
        <p name="pergunta" id="pergunta">{{ pergunta }}</p>
      
        <input type="submit" />
      </form>
</body>
</html>